targets:
  # Bloco de definição de ambientes (targets) do Databricks Asset Bundle

  dev:
    # Target de desenvolvimento

    permissions:
      # Define permissões aplicadas aos recursos criados nesse target
      - group_name: data_engineer_gp
        level: CAN_MANAGE
        # O grupo data_engineer_gp terá permissão total de gerenciamento
        # sobre os artefatos deployados nesse ambiente

    presets:
      # Presets aplicam comportamentos padrão aos recursos criados no target

      trigger_pause_status: PAUSED
      # Jobs são criados pausados por padrão
      # Evita execuções automáticas inesperadas em DEV

      source_linked_deployment: False
      # Indica se o deploy está ligado diretamente ao código fonte (ex. pasta git_folder)

      tags:
        environment: ${bundle.target}
        # Tag padrão aplicada aos recursos
        # Ajuda em governança, rastreabilidade e FinOps

    variables:
      # Sobrescrita de variáveis específicas para o ambiente DEV

      storage_account: adlsbigdataddceus2dev
      # Conta de storage usada neste ambiente

      num_workers_cluster: 2
      # Valor da variável reutilizada nos arquivos de configuração

      warehouse_name: Serverless Starter Warehouse
      # Nome lógico do SQL Warehouse utilizado no DEV
